name: Go CD Pipeline

on:
  push:
    branches: [ production ]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t logistics-app .